# Generated by Django 2.0 on 2020-04-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.category')),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
    ]
