# Generated by Django 2.0 on 2020-04-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
    ]
