# Generated by Django 2.0 on 2020-04-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0005_auto_20200413_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
    ]
