# Generated by Django 2.0 on 2020-04-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0007_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sign',
            },
        ),
    ]
