# Generated by Django 2.0 on 2020-05-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0008_sign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign',
        ),
    ]
