# Generated by Django 2.0 on 2020-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0010_register_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('resumeupload', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'career',
            },
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='user',
        ),
        migrations.DeleteModel(
            name='register_table',
        ),
    ]
