# Generated by Django 2.0 on 2020-05-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0011_auto_20200506_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='resumeupload',
        ),
        migrations.AddField(
            model_name='career',
            name='sentfile',
            field=models.FileField(default='', max_length=200, upload_to=''),
        ),
    ]
