# Generated by Django 2.0 on 2020-05-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0016_auto_20200515_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='experience',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
